"""add image path column and rename image url column

Revision ID: 3de68771c1d9
Revises: 222f587b068d
Create Date: 2026-05-01 11:42:18.219599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de68771c1d9'
down_revision: Union[str, Sequence[str], None] = '222f587b068d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories_db', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('categories_db', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('categories_db', 'imageUrl')
    op.add_column('products_db', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('products_db', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('products_db', 'imageUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_db', sa.Column('imageUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products_db', 'image_path')
    op.drop_column('products_db', 'image_url')
    op.add_column('categories_db', sa.Column('imageUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('categories_db', 'image_path')
    op.drop_column('categories_db', 'image_url')
    # ### end Alembic commands ###
