"""add unit price column in order items table

Revision ID: 4b4956a6e34c
Revises: c3ce292ab7fc
Create Date: 2026-05-09 11:41:00.921413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4956a6e34c'
down_revision: Union[str, Sequence[str], None] = 'c3ce292ab7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items_db', sa.Column('unit_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items_db', 'unit_price')
    # ### end Alembic commands ###
