"""add payment link column in orders table

Revision ID: 664712dc4fcf
Revises: 4b4956a6e34c
Create Date: 2026-05-11 12:28:39.362014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664712dc4fcf'
down_revision: Union[str, Sequence[str], None] = '4b4956a6e34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_db', sa.Column('payment_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_db', 'payment_link')
    # ### end Alembic commands ###
