"""add address and complement to order table

Revision ID: c3ce292ab7fc
Revises: 3de68771c1d9
Create Date: 2026-05-06 13:44:32.709011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ce292ab7fc'
down_revision: Union[str, Sequence[str], None] = '3de68771c1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_db', sa.Column('address', sa.String(), nullable=False))
    op.add_column('orders_db', sa.Column('complement', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_db', 'complement')
    op.drop_column('orders_db', 'address')
    # ### end Alembic commands ###
